# Generated by Django 5.1.6 on 2025-04-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0005_anouncements_alter_membership_user_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactions",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
